### PR TITLE
feat(cuda): Add support for cuda 12 so as to not conflict with users workflows

### PR DESCRIPTION
**Pull request by dcaustin33**
**Shortcut:** Na

**Description:** Adding support for Cuda 12 and allowing users to download the version they are using in their current workflows. FAQ documentation will be updated when this is merged

**Tests:**

- [ ] Local.
- [ ] CI.

### CODE REVIEW

**Review by tyler-galileo — APPROVED** [review]

**Comment by dcaustin33** [comment]
Currently works for both cuda11 and cuda12 - most people in the future will be using cuda 12 so think we should make that the default. Only problem being we cannot pin the cuda11 versions. @franz101 I realized late you were doing the same work but what do you think of this solution. Will wait for @elboy3 to be back before merging anything

**Comment by franz101** [comment]
@dcaustin33 where you able to make it work?

**Review by elboy3 — CHANGES_REQUESTED** [review]
This is very nice. I didn't realize you could add cuda11 to the extras without having them in the dependencies. 

We just gotta relock poetry lock file (sorry, I pushed a small change to that file)

And we gotta look into that one failing test. It looks like `self.model` may be reserved within that class. 

And then we can merge

**Comment by franz101** [comment]
Very simple pin keras to 2.15 (right now it's at 3)

**Review by franz101 — APPROVED** [review]
Make sure keras is below 2.15 (right now it's on 3)
https://github.com/rungalileo/dataquality/blob/5e1ef42cecf43d159cb79211d31d7ab07540dfb9/pyproject.toml#L120

Here TensorFlow needs to be <= 2.15.0

**Review by elboy3 — APPROVED** [review]
looking good, very nice

**Pull request merged**
