### PR TITLE
chore(deps): Bump `vaex-core` to v4.18.0 and `vaex-hdf5` to v0.14.0

### PR DESCRIPTION
**Pull request by setu4993**
**Description:** Let's see if this works 🤞🏽.

**Tests:**

- [ ] Local.
- [ ] CI.

### CODE REVIEW

**Comment by dmallon** [comment]
wow, 42 tests failing from a library version bump? impressive...

**Comment by franz101** [comment]
lets see what happens when we bump numpy:
https://github.com/rungalileo/dataquality/pull/873

**Comment by setu4993** [comment]
I think v4.18.0 might be getting yanked per discussion in https://github.com/vaexio/vaex/issues/2439.

**Comment by setu4993** [comment]
Closing for now, we'll likely need to bump to v.4.18.1 / v4.19+ whenever that comes out.

**Pull request closed without merging**
