### PR TITLE
chore: remove version check warning

### PR DESCRIPTION
**Pull request by elboy3**
**Shortcut:**
https://app.shortcut.com/galileo/story/14149/qa-bug-tc-mltc-notebooks-problem-with-creating-new-project

**Description:**
Remove the major version mismatch as noticed in ☝️ 

This concept has not been kept up with as api has been built towards more clients than just DQ 

**Tests:**

- [x] Local.
- [x] CI.

### CODE REVIEW

**Comment by elboy3** [comment]
https://app.shortcut.com/galileo/story/14149/qa-bug-tc-mltc-notebooks-problem-with-creating-new-project

**Review by setu4993 — CHANGES_REQUESTED** [review]
API key in the notebook 😬.

**Comment by elboy3** [comment]
> API key in the notebook 😬.

Gone! with interactive rebase to remove from history

**Review by setu4993 — APPROVED** [review]
No more 🚨s for version mismatches.

**Pull request merged**
