### PR TITLE
Raise error if trainer eval strat is steps

### PR DESCRIPTION
**Pull request by elboy3**
We only support epoch

### CODE REVIEW

**Comment by Ben-Epstein** [comment]
@elboy3 based on this convo we may not need this https://galileoteamworkspace.slack.com/archives/C01ND14PPCP/p1686322628983019

**Review by Ben-Epstein — CHANGES_REQUESTED** [review]
@elboy3 i believe with [this pr](https://github.com/rungalileo/dataquality/pull/660) we now support steps. Can you test before merging this? We can close it if it's now supported

**Review by setu4993 — APPROVED** [review]

**Review by anthonycorletti — APPROVED** [review]

**Comment by anthonycorletti** [comment]
> This pull request has been identified as stale. Please leave a comment if it's still current or it'll be closed.

😢

**Comment by elboy3** [comment]
> > This pull request has been identified as stale. Please leave a comment if it's still current or it'll be closed.
> 
> 😢

👋

**Comment by anthonycorletti** [comment]
> > > This pull request has been identified as stale. Please leave a comment if it's still current or it'll be closed.
> > 
> > 
> > 😢
> 
> 👋

👋

**Pull request closed without merging**
